apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-microservice
  labels:
    app: template-microservice
spec:
  replicas: 1
  template:
    metadata:
      name: template-microservice
      labels:
        app: template-microservice
        role: rolling-update
    spec:
      containers:
        - name: template-microservice
          image: pradnyilk/template-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
      restartPolicy: Always
  selector:
    matchLabels:
      app: template-microservice