spring:
  application:
    name: template-microservice
  cloud:
    consul:
      host: consul-consul-server
      port: 8500
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"