spring:
  application:
    name: template-microservice
  cloud:
    consul:
      host: 172.28.138.102
      port: 30213
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"